"""Initial migration

Revision ID: 927dbe95bc5d
Revises: 
Create Date: 2025-10-29 18:32:47.708029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927dbe95bc5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atendido_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_atencion', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_usuario_municipio_asunto_estado', ['usuario_id', 'municipio', 'asunto', 'estado'])
        batch_op.create_foreign_key(None, 'administradores', ['atendido_por'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'administradores', ['registrado_por'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('registrado_por')

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_usuario_municipio_asunto_estado', type_='unique')
        batch_op.drop_column('fecha_atencion')
        batch_op.drop_column('atendido_por')

    # ### end Alembic commands ###
